  - name: Set authorized key for root
    authorized_key:
      user: root
      key: '{{ item }}'
      state: present
    with_file:
      - ../files/ssh-keys/daro.pub

  - name: Create users assigns to group, set password.
    user:
      name: "{{ item.name }}"
      state: present
      shell: /bin/bash
      password: "{{ item.password }}"
      groups: "{{ item.groups }}"
    with_items:
      - { name: 'daro',
          groups: 'sudo',
          password: "{{ daro_password_hash }}",
          }

  - name: Add ssh-keys for users.
    authorized_key:
      user: "{{ item.name }}"
      key: "{{ item.sshkey }}"
      state: present
      exclusive: True
    with_items:
      - { name: 'daro',
          sshkey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDBeXGn0+2z/69MYQrVp1jZLlY5IipUQzyPDZ0Ww1ZmUREDkv0uBhMG4JD131KziMIaMrtIG/s0QroC80WllwYrfqDUxLCxlpLvqBdxrxbaVBhZUcPfB1AWG3A1NwFbs9fA+bMHQA9LBDMQM+bLJSshClkG+YvWtZVtXk0XhMt01J6sTol3JP3XhIbkWQ6NguIggKoSqksD72jFvbRwQbMQm9gZo4jF713NS8DgRvn4wTXtfgmT2NGPIjois+N/Ti/P+lOo4J59PhNEZqVIN0yLqkJ7mhdIxUf+Mcy61+qotpbvF/qls79nHmvTSg6Yr7s+zwjZBII8KVsi+m3D1nPV daro@windowsD"
          }
