- name: add docker apt-key
  apt_key: 
    url: https://download.docker.com/linux/ubuntu/gpg 
    state: present 

- name: Add docker repo
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present
    update_cache: yes

- name: install packages for kubelet
  package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - kubelet 
    state: present

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes